# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "My awesome app"
    lane :distribute do
        build_android_app(
            task: "clean build assembleDebug",
            properties: {"versionCode" => 1, "versionName" => "0.0.1"}
        )
            #app: "1:300872815354:android:8f814cb3b805d30d60af43",
        firebase_app_distribution(

            serviceCredentialsFile="sequre-c2db1-4bced33605f1.json",
            testers: "melshabory@overcoffesolution.com,",
            release_notes: "First Demo",
            firebase_cli_path:  File.exist?("../firebase-tools-linux") ? "../firebase-tools-linux" : "/firebase-tools-linux" # for pipeline
        )
      end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
